# Name of your site (displayed in the header)
name: CareSens® Dual

# Short bio or description (displayed in the header)
description: Dispositivo para la medición de glucosa en sangre para diabeticos

home: CareSens® Dual

lema: 40 años al servicio del cliente
lema2: 40 años trabajando para servirte

# Manuales & PDFs (pdf)

n1: Manual equipo
p1: manual_equipo_caresens_dual.pdf
thumb1: caresens_dual.jpg
n2: Caresens Pro
p2: manual_tiras_glucosa_dual_pro.pdf
thumb2: caresens_pro.jpg 
n3: Ketosens
p3: manual_tiras_cetona_ketosens.pdf
thumb3: caresens_ketosens.jpg

# Pascual y Furio Valencia CENTRAL
valencia: Central Valencia
city: Paterna, Valencia
location: c/ Islas Canarias nº1, Pol. Ind. Fuente del Jarro 46988
phone: +34 900 877 453
email: info@pascualyfurio.com

# Pascual y Furio Catalunya
catalunya: Del. Cataluña 
city2: Badalona, España
location2: Plaza del Xarol 44-B Polígono les Guixeres 08915
phone2: +34 934 463 490
email2: marketing@pascualyfurio.com

# Pascual y Furio 
xxx: Del. XXX
city3: XXX, España
location3: Plaza del Xarol 44-B Polígono les Guixeres 08915
phone3: +34 934 463 490
email3: info@pascualyfurio.com

# Pascual y Furio 
xxxx: Del. XXX
city4: XXX, España
location4: c/ Islas Canarias nº1, Pol. Ind. Fuente del Jarro 46988
phone4: +34 900 877 453
email4: info@pascualyfurio.com

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 
logo: 

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  instagram:
  twitter:
  linkedin:
  pinterest:
  youtube:
  googleplus: 
  tripadvisor:
  flickr:
  github:
  behance:  
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  rss: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://diabetespyf.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/bio"
    values:
      image: true
